on:
  pull_request:
    branches: [main]

name: Integration

jobs:
  build-cache:
    name: Build cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - name: Cargo build
        run: cargo build

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/install-tools
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-readme
          version: latest
      - uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-sort
          version: latest
      - name: Lint
        run: cargo make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build-cache
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/install-tools
      - uses: taiki-e/install-action@v1
        with:
          tool: "nextest"
      - name: Run Test
        run: cargo make test
        env:
          NEXTEST_PROFILE: ci
